# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Home/Pozniak/Dokumenty/Wyklady/PUF-EiTI/projekty/serial_zybo_z7/vivado/zybo_z7.xdc

# IP: ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll}]
